name: UIAutomation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ./ui.betika
          npm ci

      - name: Run Playwright tests
        run: |
          cd ./ui.betika
          npx playwright test

      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: playwright-artifacts
          path: |
            ./ui.betika/playwright-report/
            ./ui.betika/test-results/

      - name: Publish JUnit test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: ./ui.betika/playwright-report/results.xml
